version: '3.9'
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - server-python-django
      - piiano-vault
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api/
  db:
    image: postgres
    #volumes:
    #  - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  server-python-django:
    build: ./server/python-django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./server/python-django:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/postgres
      PVAULT_BASE_URL: http://piiano-vault:${SERVER_API_PORT}
      PVAULT_ADMIN_API_KEY: ${PVAULT_ADMIN_API_KEY}

  vaultdb:
    image: postgres:${PSQL_VERSION}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432

  piiano-vault:
    image: ${PVAULT_SERVER_DOCKER_TAG}
    #volumes:
    #  - ./data/vaultdb:/var/lib/postgresql/data
    depends_on:
      - vaultdb
    init: true
    environment:
      - PVAULT_DB_HOSTNAME=vaultdb
      - PVAULT_DB_NAME=${PVAULT_DB_NAME}
      - PVAULT_DB_USER=${PVAULT_DB_USER}
      - PVAULT_DB_PASSWORD=${PVAULT_DB_PASSWORD}
      - PVAULT_DB_PORT=${PVAULT_DB_PORT}

      - PVAULT_SERVICE_ADMIN_API_KEY=${PVAULT_ADMIN_API_KEY}

      - PVAULT_SERVICE_LISTEN_ADDR=${PVAULT_SERVER_LISTEN_ADDR}
      - PVAULT_SERVICE_ARCHIVE_PRUNE_INTERVAL=${PVAULT_SERVICE_ARCHIVE_PRUNE_INTERVAL:-0}

      - PVAULT_AUDIT_LOG_DIR=${SHARED_AUDIT_DIR}
      - PVAULT_LOG_DATADOG_ENABLE=${PVAULT_LOG_DATADOG_ENABLE:-none}
      - PVAULT_LOG_CUSTOMER_ENV=${PVAULT_LOG_CUSTOMER_ENV}
      - PVAULT_LOG_CUSTOMER_IDENTIFIER=${PVAULT_LOG_CUSTOMER_IDENTIFIER}
      - PVAULT_SENTRY_ENABLE=${PVAULT_SENTRY_ENABLE}
      - PVAULT_FORCE_ACCESS_REASON=${PVAULT_FORCE_ACCESS_REASON}

      - PVAULT_DEVMODE=${PVAULT_DEVMODE}
      - PVAULT_SERVICE_ADMIN_MAY_READ_DATA=${PVAULT_SERVICE_ADMIN_MAY_READ_DATA}
      - PVAULT_TLS_ENABLE=${PVAULT_TLS_ENABLE}
      - PVAULT_DB_REQUIRE_TLS=${PVAULT_DB_REQUIRE_TLS}

      - PVAULT_SERVICE_LICENSE=${PVAULT_SERVICE_LICENSE}
    ports:
      - ${SERVER_API_PORT}:${SERVER_API_PORT}
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
          max-file: "2"
