filebeat.inputs:
- type: container
  containers.ids:
    - vault-demo-server-python-django-1
    - vault-demo-piiano-vault-1
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"

output.logstash:
  hosts: ["logstash:5001"]


# Add the following lines to enable debug logging
# logging.level: debug
# logging.to_files: false
# logging.to_syslog: false
# logging.metrics.enabled: false